### ISSUE TITLE
Unable to initialize ZTV

### ISSUE THREAD

**Issue by tronsgaard** [henryroe/ztv#1] opened 2015-04-22 14:31 UTC
This looks like a great piece of software - especially for those users that are moving away from IDL. Unfortunately I am not able to start it. 

I am using Ubuntu 14.04 and Python 2.7.6 with the following versions of the required packages:

astropy == 1.0.2
wxPython == 2.8.12.1
matplotlib == 1.4.3
psutil == 2.2.1

Here is the calling sequence and error message that appears a few seconds after the command is fired.

> import ztv
> z = ztv.ZTV()

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ztv/file_picker.py", line 316, in on_current_textctrl_changed
    self.validate_current_textctrl_value()
  File "/usr/local/lib/python2.7/dist-packages/ztv/file_picker.py", line 238, in validate_current_textctrl_value
    'Press enter in this field to load')
  File "/usr/local/lib/python2.7/dist-packages/ztv/ztv_lib.py", line 32, in set_textctrl_background_color
    force_textctrl_color_update(textctrl)
  File "/usr/local/lib/python2.7/dist-packages/ztv/ztv_lib.py", line 11, in force_textctrl_color_update
    can_accept_focus_mask = [(a.CanAcceptFocus() and (a is not textctrl)) for a in children]
AttributeError: 'Choice' object has no attribute 'CanAcceptFocus'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ztv/file_picker.py", line 316, in on_current_textctrl_changed
    self.validate_current_textctrl_value()
  File "/usr/local/lib/python2.7/dist-packages/ztv/file_picker.py", line 238, in validate_current_textctrl_value
    'Press enter in this field to load')
  File "/usr/local/lib/python2.7/dist-packages/ztv/ztv_lib.py", line 32, in set_textctrl_background_color
    force_textctrl_color_update(textctrl)
  File "/usr/local/lib/python2.7/dist-packages/ztv/ztv_lib.py", line 11, in force_textctrl_color_update
    can_accept_focus_mask = [(a.CanAcceptFocus() and (a is not textctrl)) for a in children]
AttributeError: 'Choice' object has no attribute 'CanAcceptFocus'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/ztv/ztv.py", line 1218, in **init**
    control_panels_to_load=control_panels_to_load)
  File "/usr/local/lib/python2.7/dist-packages/ztv/ztv.py", line 692, in **init**
    self.controls_notebook = ControlsNotebook(self)  
  File "/usr/local/lib/python2.7/dist-packages/ztv/ztv.py", line 568, in **init**
    self.AddPanelAndStoreID(cur_panel(self), cur_title)
  File "/usr/local/lib/python2.7/dist-packages/ztv/source_panel.py", line 122, in **init**
    self.curfile_file_picker = FilePicker(self, title='')
  File "/usr/local/lib/python2.7/dist-packages/ztv/file_picker.py", line 90, in **init**
    self._on_load(self.current_textctrl_GetValue())
  File "/usr/local/lib/python2.7/dist-packages/ztv/file_picker.py", line 152, in _on_load
    set_textctrl_background_color(self.current_textctrl, 'ok')
  File "/usr/local/lib/python2.7/dist-packages/ztv/ztv_lib.py", line 32, in set_textctrl_background_color
    force_textctrl_color_update(textctrl)
  File "/usr/local/lib/python2.7/dist-packages/ztv/ztv_lib.py", line 11, in force_textctrl_color_update
    can_accept_focus_mask = [(a.CanAcceptFocus() and (a is not textctrl)) for a in children]
AttributeError: 'Choice' object has no attribute 'CanAcceptFocus'

**Comment by henryroe** [comment] 2015-04-22 15:54
Thanks for your interest & finding this problem.

I think the issue is some combination of that version of wx and ubuntu.  (In all of my testing environments wx.Choice has a CanAcceptFocus method, so I cannot replicate the bug.)

I've added a `hasattr(...'CanAcceptFocus')` to `ztv_lib.py`, which should catch for this case.

**Comment by henryroe** [comment] 2015-04-22 15:58
Hi, 
I’ve uploaded what I hope is the fix to github.

Could you grab the latest (only change is in ztv_lib.py) and test in your environment?  Please then let me know what you find.

(I have my suspicions that if this bug cropped up with that version of wx and ubuntu, there could be other quick fixes needed.)

I’ll leave this issue open until I hear from you (or close it in a few days under assumption that no news is good news).

thanks,
-Henry

**Comment by tronsgaard** [comment] 2015-04-22 19:23
Hi,

Thanks for looking into this - I replaced line 11 in ztv_lib.py, and it definitely made the error message go away, but there is still no window. After ~15 seconds, Python returns "Segmentation fault (core dumped)" and nothing else.

I tried upgrading wxPython using pip, but it is not able to see version 2.9.1.1. I then remoed the wxPython package (using pip), and after that I was not able to install it again with pip. Reinstalling the Ubuntu package python-wxgtk2.8 brought it back though.

/René

**Comment by henryroe** [comment] 2015-04-22 19:43
I’m looking in to it.  Up until now all development/testing of ztv has been on OS X.  Because I will eventually need ztv working on ubuntu (or similar) for myself, I’ve set up an ubuntu VM, am able to replicate this core dump, and am looking into it.  I’ll let you know what I figure out.  

thanks for your patience,
-Henry

**Comment by henryroe** [comment] 2015-04-22 23:10
I tested on Ubuntu 14.04 running in a VM & was able to replicate the bugs that you ran into. (Plus one or two others.)  I've fixed them.

I've released 0.1.0post1 to both github & pypi.

ztv now mostly works on linux/ubuntu.  The issues I know about are: 1) performance was laggier on my VM by a good margin (but I didn't allow it much resources), 2) colormap bitmaps don't show up in dropdown menus, 3) ctrl-# to switch between cursor modes only works after you've clicked in the primary image frame.

Hope this helps.  I will close out this issue, but please feel free to let me know if you run into additional problems.
-Henry

**Closed as completed by henryroe** 2015-04-22 23:10 UTC
